package de.bitsharesmunich.graphenej;

/**
 * Created by nelson on 1/12/17.
 */

public enum ObjectType {
    BASE_OBJECT,
    ACCOUNT_OBJECT,
    ASSET_OBJECT,
    FORCE_SETTLEMENT_OBJECT,
    COMMITTEE_MEMBER_OBJECT,
    WITNESS_OBJECT,
    LIMIT_ORDER_OBJECT,
    CALL_ORDER_OBJECT,
    CUSTOM_OBJECT,
    PROPOSAL_OBJECT,
    OPERATION_HISTORY_OBJECT,
    WITHDRAW_PERMISSION_OBJECT,
    VESTING_BALANCE_OBJECT,
    WORKER_OBJECT,
    BALANCE_OBJECT,
    GLOBAL_PROPERTY_OBJECT,
    DYNAMIC_GLOBAL_PROPERTY_OBJECT,
    ASSET_DYNAMIC_DATA,
    ASSET_BITASSET_DATA,
    ACCOUNT_BALANCE_OBJECT,
    ACCOUNT_STATISTICS_OBJECT,
    TRANSACTION_OBJECT,
    BLOCK_SUMMARY_OBJECT,
    ACCOUNT_TRANSACTION_HISTORY_OBJECT,
    BLINDED_BALANCE_OBJECT,
    CHAIN_PROPERTY_OBJECT,
    WITNESS_SCHEDULE_OBJECT,
    BUDGET_RECORD_OBJECT,
    SPECIAL_AUTHORITY_OBJECT
}
